### ISSUE TITLE
misspell_fixer -r changes file permissions

### ISSUE THREAD

**Issue by tbeu** [vlajos/misspell_fixer#10]
There is a known bug of ```sed -i``` on Windows MinGW that the file is set to read-only. The workaround is to call ```attrib -R``` afterwards.

**Comment by vlajos** [comment]
Hi,
Do you see an easy way to test this without access to windows environment?

Best regards,
Lajos

**Comment by tbeu** [comment]
I could test it.

**Comment by tbeu** [comment]
One other test is to force the read-only attribute after ```sed -i``` to emulate the [bug](http://stackoverflow.com/questions/1823591/sed-creates-un-deleteable-files-in-windows).

**Comment by vlajos** [comment]
Hi,

I have just pushed a change. Could you please test it?

Best regards,
Lajos

**Comment by tbeu** [comment]
Well done. Changed file (with fixed misspells) is no longer read-only.
