### ISSUE TITLE
Preserve CRLF eol

### ISSUE THREAD

**Issue by tbeu** [vlajos/misspell_fixer#9]
I run misspell_fixer.sh on Win32 using either MinGW or Cygwin environment. It would be nice if CRLF line endings are preserved (and not changed to LF automatically). What I do now is to run unix2dos for every changed file afterwards.

**Comment by szepeviktor** [comment]
Please consider using LF during development on any operating system.

**Comment by vlajos** [comment]
@tbeu I have just added `-b` to `sed` in normal mode which should make it keeping the line endings intact. (This has been implemented in fast mode already.) Could you please test it?

**Comment by tbeu** [comment]
Thanks. Fix confirmed.
